export const artists = [
  {
    id: 'levizja',
    name: 'LËVIZJA',
    realName: 'Dren Asllani',
    origin: 'Prishtinë',
    genres: ['Techno', 'Industrial'],
    bio: "Dren Asllani has been at the heart of Prishtina's underground since 2017, forging a sound that blends relentless industrial percussion with hypnotic, looping textures. Resident at Soma Club and regular on the Berghain circuit.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com', ra: 'https://ra.co' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'LIVE @ Tresor Berlin 2025',
    tags: ['Resident', 'Producer'],
  },
  {
    id: 'arbri',
    name: 'ARBRI',
    realName: 'Arber Krasniqi',
    origin: 'Gjakovë',
    genres: ['Minimal Techno', 'Dub Techno'],
    bio: "Deep, rolling minimal techno shaped by years of after-hours residencies across the Balkans. ARBRI's sets are patient, hypnotic marathons that build pressure over hours. Known for meticulous mixing and dark, dubbed-out atmospheres.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com', ra: 'https://ra.co' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'SOMA CLUB — 6hr B2B Set',
    tags: ['Resident', 'DJ'],
  },
  {
    id: 'vera-x',
    name: 'VERA X',
    realName: 'Vera Berisha',
    origin: 'Prishtinë',
    genres: ['Dark Techno', 'EBM'],
    bio: "One of the most powerful and distinctive voices emerging from the Balkans, Vera Berisha's VERA X project fuses Eastern European EBM traditions with Kosovar grit. Her sets are confrontational and cathartic.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com', bandcamp: 'https://bandcamp.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'SUBTERRANEA FEST 2025 — FULL SET',
    tags: ['Producer', 'Live Act'],
  },
  {
    id: 'kryptic',
    name: 'KRYPTIC',
    realName: 'Kryp Selimi',
    origin: 'Mitrovicë',
    genres: ['Acid Techno', 'Rave'],
    bio: "KRYPTIC brings the relentless energy of early 90s acid rave to Kosovo's underground. Raw 303 lines and punishing kick drums define a sound that ignites dancefloors from Mitrovicë to Zürich.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'ACID PARTY PRISHTINA — LIVE',
    tags: ['DJ', 'Producer'],
  },
  {
    id: 'fold',
    name: 'FOLD',
    realName: 'Fisnik Gashi',
    origin: 'Prizren',
    genres: ['Experimental', 'Noise'],
    bio: 'Under the alias FOLD, Fisnik Gashi explores the outer limits of electronic music — noise, drone, and deconstructed club music collide in performances that challenge assumptions about what a DJ set can be.',
    links: { soundcloud: 'https://soundcloud.com', bandcamp: 'https://bandcamp.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'ECHO CHAMBER VOL.3 — LIVE A/V',
    tags: ['Experimental', 'Live Act'],
  },
  {
    id: 'hana',
    name: 'HANA',
    realName: 'Hana Gashi',
    origin: 'Prishtinë',
    genres: ['House', 'Garage', 'UK Bass'],
    bio: 'HANA bridges underground house and UK garage with a Kosovar sensibility, bringing warmth and groove to a scene that often skews dark. Her DJ sets are masterclasses in reading a room and building euphoria.',
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'NOCTURNAL VOL.11 — OPENING SET',
    tags: ['DJ', 'Resident'],
  },
  {
    id: 'skena',
    name: 'SKENA',
    realName: 'Skena Collective',
    origin: 'Prishtinë',
    genres: ['Acid', 'Tekno'],
    bio: "SKENA is a three-piece DJ collective who cut their teeth at free parties in the hills outside Prishtina before becoming one of the city's most requested acts. Acid lines, hard tekno, and zero compromise.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'FREE PARTY GËRMIA — SUNRISE SET',
    tags: ['Collective', 'DJ'],
  },
  {
    id: 'disa',
    name: 'DISA',
    realName: 'Disa Morina',
    origin: 'Pejë',
    genres: ['Ambient', 'Drone', 'Downtempo'],
    bio: "Disa Morina's ambient and drone work under the DISA alias occupies the quieter hours and the in-between spaces. Her music soundtracks Kosovar landscapes — vast, haunted, and quietly breathtaking.",
    links: { soundcloud: 'https://soundcloud.com', bandcamp: 'https://bandcamp.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'AMBIENT SERIES — LIVE RECORDING',
    tags: ['Producer', 'Ambient'],
  },
]

export const events = [
  {
    id: 'void-01',
    title: 'VOID',
    subtitle: 'Monthly Techno Ritual',
    date: '2026-05-02',
    time: '23:00 – 07:00',
    venue: 'Soma Club',
    address: 'Rr. Migjeni 14, Prishtinë',
    lineup: ['LËVIZJA', 'ARBRI', 'Guest TBA'],
    description: 'VOID returns for its monthly residency at Soma Club. Five hours of uncompromising techno across two floors. Doors at 23:00, no early entry.',
    ticketLink: 'https://tickets.example.com',
    price: '€8 advance / €12 door',
    soldOut: false,
    featured: true,
    posterColor: '#1a0a2e',
  },
  {
    id: 'nocturnal-12',
    title: 'NOCTURNAL VOL.12',
    subtitle: 'All Night Long',
    date: '2026-05-09',
    time: '22:00 – 08:00',
    venue: 'District',
    address: 'Rr. Nëna Terezë, Prishtinë',
    lineup: ['VERA X', 'HANA', 'KRYPTIC'],
    description: 'The twelfth edition of our flagship club night. Three residents, three rooms, one relentless night. This edition features the long-awaited Prishtina debut of VERA X\'s new live hardware set.',
    ticketLink: 'https://tickets.example.com',
    price: '€10 advance / €15 door',
    soldOut: false,
    featured: true,
    posterColor: '#0a1a0f',
  },
  {
    id: 'basement-5',
    title: 'BASEMENT SERIES #5',
    subtitle: 'Underground Sessions',
    date: '2026-05-23',
    time: '23:00 – 06:00',
    venue: 'Undisclosed Venue',
    address: 'Location revealed 24h before',
    lineup: ['FOLD', 'SKENA', 'DISA'],
    description: 'Our intimate Basement Series continues in an undisclosed location. Capacity 150. Experimental electronics and acid-tinged techno in close quarters. Sign up for the location reveal mailing list.',
    ticketLink: 'https://tickets.example.com',
    price: '€6 advance only',
    soldOut: true,
    featured: false,
    posterColor: '#1a1100',
  },
  {
    id: 'metamorphose',
    title: 'METAMORPHOSE',
    subtitle: 'One Night, One Room',
    date: '2026-06-06',
    time: '22:00 – 07:00',
    venue: 'JUG 2',
    address: 'Rr. Fehmi Agani, Prishtinë',
    lineup: ['ARBRI', 'LËVIZJA', 'VERA X', 'International Guest'],
    description: 'A special single-room night celebrating transformation. Four sets, no gap, no compromise. International booking to be announced.',
    ticketLink: 'https://tickets.example.com',
    price: '€12 advance / €18 door',
    soldOut: false,
    featured: true,
    posterColor: '#0f0a1a',
  },
  {
    id: 'subterranea',
    title: 'SUBTERRANEA FESTIVAL',
    subtitle: '2nd Edition',
    date: '2026-06-13',
    time: 'Sat 20:00 – Sun 14:00',
    venue: 'Abandoned Factory, Mitrovicë',
    address: 'GPS coordinates on ticket',
    lineup: ['Full lineup TBA', 'LËVIZJA', 'VERA X', 'KRYPTIC', 'FOLD', 'SKENA', '+ International Guests'],
    description: "Kosovo's premier underground festival returns to the decommissioned industrial complex outside Mitrovicë for its second edition. Three stages, camping, art installations, and 18 hours of continuous music.",
    ticketLink: 'https://tickets.example.com',
    price: '€30 weekend / €20 Saturday / €15 Sunday',
    soldOut: false,
    featured: false,
    posterColor: '#0a0f1a',
  },
  {
    id: 'transit',
    title: 'TRANSIT OUTDOOR',
    subtitle: 'Summer Open Air',
    date: '2026-07-12',
    time: '17:00 – 03:00',
    venue: 'Gërmia Park',
    address: 'Gërmia, Prishtinë',
    lineup: ['HANA', 'ARBRI', 'LËVIZJA', 'DISA (Ambient Stage)'],
    description: 'Our summer outdoor event returns to the forest clearings of Gërmia Park. A rare chance to experience electronic music under the Kosovo sky. Ambient stage hosted by DISA.',
    ticketLink: 'https://tickets.example.com',
    price: '€15 advance / €20 door',
    soldOut: false,
    featured: false,
    posterColor: '#0a1a0a',
  },
  {
    id: 'dark-matter',
    title: 'DARK MATTER FEST',
    subtitle: '3-Day Multivenue Festival',
    date: '2026-07-25',
    time: 'Fri–Sun, doors at 21:00',
    venue: 'Multiple Venues, Prishtinë',
    address: 'Prishtinë City Centre',
    lineup: ['Full Lineup TBA', 'All TK Artists', '+ 12 International Acts'],
    description: 'Three days. Four venues. Kosovo\'s biggest electronic music festival returns, spreading across the cultural venues and clubs of central Prishtina.',
    ticketLink: 'https://tickets.example.com',
    price: '€45 3-day pass / €20 per day',
    soldOut: false,
    featured: false,
    posterColor: '#1a0808',
  },
  {
    id: 'echo-4',
    title: 'ECHO CHAMBER VOL.4',
    subtitle: 'Experimental Electronic Night',
    date: '2026-08-09',
    time: '21:00 – 05:00',
    venue: 'Kino Armata',
    address: 'Rr. Luan Haradinaj, Prishtinë',
    lineup: ['FOLD', 'DISA', 'SKENA'],
    description: 'The fourth edition of our experimental night takes over the cinema space of Kino Armata. Expect live audio-visual performances, installations, and sets that go beyond the dancefloor.',
    ticketLink: 'https://tickets.example.com',
    price: '€8 advance / €12 door',
    soldOut: false,
    featured: false,
    posterColor: '#0f1a1a',
  },
]
