export const artists = [
  {
    id: 'altin',
    name: 'Altin Boshnjaku',
    realName: 'Altin Boshnjaku',
    origin: 'Gjakova',
    genres: ['Techno', 'Industrial'],
    bio: "Altin Boshnjaku (Gjakova, Kosovo) has been part of the underground scene since late 2014. His sets fuse hypnotic techno, minimal, and deep house with rolling grooves and careful selection. Long-time resident at Zone Club’s Electronic Series (supported Tobi Neumann, Cassy and others) and a regular at UNUM Festival.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com', ra: 'https://ra.co' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'LIVE @ Tresor Berlin 2025',
    tags: ['Resident', 'Producer'],
  },
  {
    id: 'oda',
    name: 'Oda Haliti',
    realName: 'Oda Haliti',
    origin: 'Prishtinë',
    genres: ['Minimal Techno', 'Dub Techno'],
    bio: "Oda Haliti is a dynamic DJ, producer, and cultural activist based in Prishtina. Known for her genre-bending sound, she weaves together experimental electronic beats, acid disco, and minimal techno to create an electrifying dance floor groove. Rising through the regional underground scene with her raw talent, she has performed at major international stages, including Berghain and Kala Festival. Beyond her solo performances, Oda pushes creative boundaries through collaborative projects like Tandem and In•Tendo, cementing her role as a vital force in the Balkan electronic music landscape.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com', ra: 'https://ra.co' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'SOMA CLUB — 6hr B2B Set',
    tags: ['Resident', 'DJ'],
  },
  {
    id: 'uran',
    name: 'Uran B.',
    realName: 'Uran Badivuku',
    origin: 'Prishtinë',
    genres: ['Dark Techno', 'EBM'],
    bio: "Uran Badivuku, widely known as Uran B., is a pioneering DJ, producer, and cultural organizer based in Prishtina. As a driving force behind the local electronic music scene, he co-founded the influential collective and organization Hapësira, which has played a major role in shaping the contemporary underground house and techno movement in Kosovo.  With a forward-thinking approach that dates back to the early days of the post-war warehouse scene at Rilindja, Uran has spent over a decade breaking musical routines and building an international platform for Balkan artists. His style and sets bridge the gap between forward-thinking, industrial-leaning sounds and a deeply rooted collective vision.  Known as an objective and critical voice for the arts, he continually redefines the relationship between the DJ booth and the dance floor, championing collectivism and resilience in the digital and cultural industries.  Uran’s influence extends beyond his own productions and performances, as he has been instrumental in fostering a vibrant community of artists and audiences through his work with Hapësira and his commitment to creating inclusive spaces for electronic music in Kosovo and the wider region.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com', bandcamp: 'https://bandcamp.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'SUBTERRANEA FEST 2025 — FULL SET',
    tags: ['Producer', 'Live Act'],
  },
  {
    id: 'mim',
    name: 'MiM',
    realName: 'Nazim Maxhuni',
    origin: 'Prishtinë',
    genres: ['Acid Techno', 'Rave'],
    bio: "Nazim Maxhuni, widely known as DJ MiM, is an established figure in Prishtina's music scene with 25 years of experience, during which he has helped shape the techno and electronic music scene in Kosovo and beyond. With a versatile and dynamic approach to mixing, he is known for bringing high energy and a smooth flow to dance floors, drawing from various electronic and house-oriented sounds.Over the years, he has built a reputation for reading the crowd, blending rhythm with a deep connection to the regional nightlife. His sets capture the vibrant, energetic spirit of the local club and event scene while remaining a staple for a broad audience.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'ACID PARTY PRISHTINA — LIVE',
    tags: ['DJ', 'Producer'],
  },
  {
    id: 'toske',
    name: 'TOSKE',
    realName: 'Fatos Cunaku',
    origin: 'Prishtinë',
    genres: ['Experimental', 'Noise'],
    bio: 'Under the alias FOLD, Fisnik Gashi explores the outer limits of electronic music — noise, drone, and deconstructed club music collide in performances that challenge assumptions about what a DJ set can be.',
    links: { soundcloud: 'https://soundcloud.com', bandcamp: 'https://bandcamp.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'ECHO CHAMBER VOL.3 — LIVE A/V',
    tags: ['Experimental', 'Live Act'],
  },
  {
    id: 'hana',
    name: 'HANA',
    realName: 'Hana Gashi',
    origin: 'Prishtinë',
    genres: ['House', 'Garage', 'UK Bass'],
    bio: 'HANA bridges underground house and UK garage with a Kosovar sensibility, bringing warmth and groove to a scene that often skews dark. Her DJ sets are masterclasses in reading a room and building euphoria.',
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'NOCTURNAL VOL.11 — OPENING SET',
    tags: ['DJ', 'Resident'],
  },
  {
    id: 'skena',
    name: 'SKENA',
    realName: 'Skena Collective',
    origin: 'Prishtinë',
    genres: ['Acid', 'Tekno'],
    bio: "SKENA is a three-piece DJ collective who cut their teeth at free parties in the hills outside Prishtina before becoming one of the city's most requested acts. Acid lines, hard tekno, and zero compromise.",
    links: { soundcloud: 'https://soundcloud.com', instagram: 'https://instagram.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'FREE PARTY GËRMIA — SUNRISE SET',
    tags: ['Collective', 'DJ'],
  },
  {
    id: 'disa',
    name: 'DISA',
    realName: 'Disa Morina',
    origin: 'Pejë',
    genres: ['Ambient', 'Drone', 'Downtempo'],
    bio: "Disa Morina's ambient and drone work under the DISA alias occupies the quieter hours and the in-between spaces. Her music soundtracks Kosovar landscapes — vast, haunted, and quietly breathtaking.",
    links: { soundcloud: 'https://soundcloud.com', bandcamp: 'https://bandcamp.com' },
    videoId: 'dQw4w9WgXcQ',
    videoLabel: 'AMBIENT SERIES — LIVE RECORDING',
    tags: ['Producer', 'Ambient'],
  },
]

export const events = [
  {
    id: 'mihai-popoviciu-next-level',
    title: 'MIHAI POPOVICIU - NEXT LEVEL',
    subtitle: 'An Experimental Concept',
    date: '2026-05-08',
    time: '22:00',
    venue: 'AMC HALL, I STAGE 2',
    address: 'Bucharest, Romania',
    lineup: ['Mihai Popoviciu', 'La Barosha', 'Baxei', 'MiM'],
    description: 'A new experimental concept where the night unfolds phase by phase, a journey through sound, atmosphere, and energy. Featuring Romanian legend and Cyclic Records boss Mihai Popoviciu, supported by rising female talent La Barosha, old school selector Baxei, and MiM — a key figure in Kosovo\'s electronic music movement.',
    ticketLink: 'https://www.rave-travel.com/event-details-en.nspx?eventid=4098',
    price: '€10 advance / €15 at door',
    soldOut: false,
    featured: true,
    posterColor: '#cc1111',
  },
  {
    id: 'unum-festival',
    title: 'UNUM FESTIVAL',
    subtitle: '5 Days Non-Stop Music',
    date: '2026-06-04',
    time: 'Thu–Mon, 24h non-stop',
    venue: 'Set Beach',
    address: 'Shengjin, Albania',
    lineup: ['Ben Klock', 'Ricardo Villalobos', 'Gerd Janson', 'Dan Andrei', 'Maher Daniel', 'Prospa', '+ 50+ International DJs'],
    description: 'Winner of Global Festival DJ Awards Ibiza 2025. Five days of non-stop electronic music against the backdrop of the Albanian Riviera. Multiple stages, beachfront location, and world-class international lineup.',
    ticketLink: 'https://unumfestival.com/tickets',
    price: '€150–€250 festival pass',
    soldOut: false,
    featured: true,
    posterColor: '#1a4f3a',
  },
  {
    id: 'sunny-hill-festival',
    title: 'SUNNY HILL FESTIVAL',
    subtitle: 'Dua Lipa Presents',
    date: '2026-07-31',
    time: 'Wed–Fri, 18:00–02:00',
    venue: 'Sunny Hill Festival Park',
    address: 'Prishtinë, Kosovo',
    lineup: ['Dua Lipa', 'International Headliners TBA', 'Kosovo Artists', 'Regional Stars'],
    description: 'Kosovo\'s premier music festival organized by global superstar Dua Lipa. Winner of the Economic Impact Award from Kosovo Chamber of Commerce. Three days of world-class entertainment celebrating Kosovo culture and international music.',
    ticketLink: 'https://sunnyhillfestival.com/tickets',
    price: '€80–€150 weekend pass',
    soldOut: false,
    featured: true,
    posterColor: '#f0eb3a',
  },
  {
    id: 'sundance-festival',
    title: 'SUNDANCE FESTIVAL',
    subtitle: 'Mountain Electronic Experience',
    date: '2026-07-09',
    time: 'Wed–Sat, 20:00–06:00',
    venue: 'Mountain Resort',
    address: 'Zvërnec, Albania',
    lineup: ['International Techno Artists', 'Albanian DJs', 'Live Performances', 'Ambient Sets'],
    description: 'Four days of electronic music in the stunning Albanian mountains. Set against breathtaking natural scenery, Sundance Festival combines world-class DJs with immersive art installations and mountain views.',
    ticketLink: 'https://sundance-festival.com/',
    price: '€100–€180 festival pass',
    soldOut: false,
    featured: true,
    posterColor: '#2a4f6a',
  },
]
