export const artists = [
  {
    id: 'altin',
    name: 'Altin Boshnjaku',
    realName: 'Altin Boshnjaku',
    origin: 'Gjakova',
    genres: ['Techno', 'Industrial'],
    bio: "Altin Boshnjaku (Gjakova, Kosovo) has been part of the underground scene since late 2014. His sets fuse hypnotic techno, minimal, and deep house with rolling grooves and careful selection. Long-time resident at Zone Club’s Electronic Series (supported Tobi Neumann, Cassy and others) and a regular at UNUM Festival.",
    links: { instagram: 'https://instagram.com/altin_boshnjaku' },
    videoId: 'K9xkDgqcuoY',
    videoLabel: 'Altin Boshnjaku — YouTube Short',
  },
  {
    id: 'oda',
    name: 'Oda Haliti',
    realName: 'Oda Haliti',
    origin: 'Prishtinë',
    genres: ['Minimal Techno', 'Dub Techno'],
    bio: "Oda Haliti is a dynamic DJ, producer, and cultural activist based in Prishtina. Known for her genre-bending sound, she weaves together experimental electronic beats, acid disco, and minimal techno to create an electrifying dance floor groove. Rising through the regional underground scene with her raw talent, she has performed at major international stages, including Berghain and Kala Festival. Beyond her solo performances, Oda pushes creative boundaries through collaborative projects like Tandem and In•Tendo, cementing her role as a vital force in the Balkan electronic music landscape.",
    links: { instagram: 'https://instagram.com/odahaliti' },
    videoId: 'E8mdBoQ00Nk',
    videoLabel: 'Oda Haliti — Live YouTube Set',
  },
  {
    id: 'uran',
    name: 'Uran B.',
    realName: 'Uran Badivuku',
    origin: 'Prishtinë',
    genres: ['Dark Techno', 'EBM'],
    bio: "Uran Badivuku, widely known as Uran B., is a pioneering DJ, and cultural organizer based in Prishtina. As a driving force behind the local electronic music scene, he co-founded the influential collective and organization Hapësira, which has played a major role in shaping the contemporary underground house and techno movement in Kosovo.  With a forward-thinking approach that dates back to the early days of the post-war warehouse scene at Rilindja, Uran has spent over a decade breaking musical routines and building an international platform for Balkan artists. Email contact uran@hapesira.space",
    links: { soundcloud: 'https://soundcloud.com/uranb', instagram: 'https://instagram.com/uranb' },
    videoId: 'qfQb4D0cdgo',
    videoLabel: 'Uran B. — Live YouTube Set',
  },
  {
    id: 'mim',
    name: 'MiM',
    realName: 'Nazim Maxhuni',
    origin: 'Prishtinë',
    genres: ['Acid Techno', 'Rave'],
    bio: "Nazim Maxhuni, widely known as DJ MiM, is an established figure in Prishtina's music scene with 25 years of experience, during which he has helped shape the techno and electronic music scene in Kosovo and beyond. With a versatile and dynamic approach to mixing, he is known for bringing high energy and a smooth flow to dance floors, drawing from various electronic and house-oriented sounds.Over the years, he has built a reputation for reading the crowd, blending rhythm with a deep connection to the regional nightlife. His sets capture the vibrant, energetic spirit of the local club and event scene while remaining a staple for a broad audience.",
    links: { instagram: 'https://instagram.com/djm1m' },
    videoId: 'w8dyB-O80p0',
    videoLabel: 'MiM — Live YouTube Set',
  },
  {
    id: 'toske',
    name: 'TOSKE',
    realName: 'Fatos Cunaku',
    origin: 'Prishtinë',
    genres: ['Experimental', 'Noise'],
    bio: 'Born and raised in Kosovo, he began producing at 16 and quickly became a prominent figure in the Balkan underground electronic scene. As the founder of RaveCultur, he has built a major platform supporting young artists and organizing events.',
    links: { soundcloud: 'https://soundcloud.com/tosketoske', instagram: 'https://www.instagram.com/toske_____/' },
    videoId: 'IY3WLsM-NGY',
    videoLabel: 'TOSKE — Live YouTube Set',
  },
  {
    id: 'anite',
    name: 'Anitë',
    realName: 'Anita Bojniku',
    origin: 'Prishtinë',
    genres: ['House', 'Techno'],
    bio: 'Born in Germany and Raised in Prishtina, Anitë blend her multicultural background into music. She is known for shaping deep,groovy underground sounds.. Mainly minimal,house and techno with hypnotic and emotional-hard grooves like you never heard before.A very important figure and part of the new wave of redefining Kosovo s underground identity, Anitë is well known and loved and respected for her unique craft of sound, energy and taste like no one you heard before. Often called the Queen Of Groove and Underground, she truly stays behind those words with dedication, hard work and kindess. Her success is not only measured by her music but also by the impact she has on the scene, inspiring many young artists and being a role model for the new generation of DJs and producers in Kosovo and the region. Anitë is a true ambassador of the Kosovo underground scene, representing it with pride and passion on the international stage. ONE OF A KIND.',
    links: { soundcloud: 'https://soundcloud.com/anita-bojniku', ra: 'https://ra.co/dj/anite', instagram: 'https://www.instagram.com/anitebojniku/' },
    videoId: 'p6M4ua6RyIg',
    videoLabel: 'ANITË — YouTube Short',
  },
  {
    id: 'liburn',
    name: 'Liburn',
    realName: 'Liburn Krasniqi',
    origin: 'Prishtinë',
    genres: ['House', 'Techno'],
    bio: '  Liburn is a Prishtina-based DJ and producer known for his dynamic sets that blend house and techno with a deep connection to the local club scene. With a career spanning over a decade, he has become a key figure in Kosovo\'s electronic music landscape, performing at major regional festivals and clubs. His sound is characterized by its energy, groove, and ability to connect with diverse audiences, making him a staple in the Balkan underground scene. Resident DJ at UNUM Festival where he has palyed a major role in shaping the event\'s musical identity, Liburn continues to push boundaries and elevate the profile of Kosovo\'s electronic music on the international stage. Well respected for his deep understanding of the dance floor and his ability to create memorable musical journeys, Liburn is a true ambassador of Kosovo\'s vibrant club culture. A king of the groove and a master of the dance floor, Liburn\'s influence extends beyond his music, as he has played a significant role in fostering community and supporting emerging talent within the local scene.',
    links: { ra: 'https://ra.co/dj/liburn', instagram: 'https://www.instagram.com/liburnilazi/' },
    videoId: 'drLpFNoQ4qU',
    videoLabel: 'Liburn b2b Rrrron — Electronic Beats',
  },
  {
    id: 'gemza',
    name: 'Gemza',
    realName: 'Gemza Burgija',
    origin: 'Prishtinë',
    genres: ['Techno', 'Experimental'],
    bio: 'Gemza is a rising Kosovan DJ and curator whose sets travel from melodic techno to raw club energy across Europe. She is also the founder of Babetronixx where she continue to host parties and support the local scene. With a unique blend of melodic techno, experimental sounds, and raw club energy, Gemza has quickly made a name for herself in the regional underground scene. Her dynamic sets have taken her to major stages across Europe, where she has captivated audiences with her ability to create immersive musical journeys. As a key figure in Kosovo\'s electronic music landscape, Gemza continues to push boundaries and elevate the profile of the local scene on the international stage.',
    links: { soundcloud: 'https://soundcloud.com/gemzab', instagram: 'https://www.instagram.com/gemzab/' },
    videoId: 'KUn6FqSje6c',
    videoLabel: 'Gemza — Urban Sessions Live',
  },
  {
    id: 'likatek',
    name: 'Likatek',
    realName: 'Episode',
    origin: 'Prishtinë',
    genres: ['House', 'Deep House'],
    bio: 'Likatek is a longtime local selector with a deep affinity for smooth house grooves and classic club energy. One of the pioneers of the Prishtina underground scene, he has been a resident at major local venues and events for over a decade, shaping the city\'s musical identity with his warm, soulful sets. With a focus on deep house and melodic rhythms, Likatek has built a loyal following in Kosovo and the region, known for his ability to create an intimate connection with the dance floor. His sets are characterized by their emotional depth and timeless groove, making him a beloved figure in the local club culture. As a key player in Prishtina\'s nightlife, Likatek continues to influence the scene with his dedication to quality music and his passion for creating memorable experiences on the dance floor.',
    links: { soundcloud: 'https://soundcloud.com/likatek', instagram: 'https://www.instagram.com/likatek' },
    videoId: 'cBobT3QAMfk',
    videoLabel: 'Likatek @ Lollipop • Drymades',
  },
  {
    id: 'besa-m',
    name: 'Besa M',
    realName: 'Besa Mati',
    origin: 'Tirana',
    genres: ['Deep House', 'Techno'],
    bio: 'Besa M blends melodic house and techno, building soulful club journeys for regional audiences. She is an old school dj female from kosovo and albania, with a career spanning over a decade. Her sets are known for their emotional depth and timeless groove, making her a beloved figure in the local club culture. With a focus on deep house and melodic rhythms, Besa M has built a loyal following in Kosovo and the region, known for her ability to create an intimate connection with the dance floor. As a key player in Prishtina\'s nightlife, Besa M continues to influence the scene with her dedication to quality music and her passion for creating memorable experiences on the dance floor.',
    links: { soundcloud: 'https://soundcloud.com/drum-and-besa', instagram: 'https://www.instagram.com/besamati/' },
    videoId: 'mfbduZO26Y8',
    videoLabel: 'Besa M — KALA Festival Set',
    tags: ['DJ', 'Producer'],
  },
  {
    id: 'leart-rama',
    name: 'Leart Rama',
    realName: 'Leart Rama',
    origin: 'Prishtinë',
    genres: ['Techno', 'Minimal'],
    bio: 'Leart Rama is a Kosovan DJ and producer whose minimal techno sets emphasize precision, atmosphere, and depth. A figure with deep roots in prishtina\'s underground scene, he has built a reputation for his meticulous selection and ability to create immersive sonic journeys. With a focus on the subtleties of techno, Leart has become a respected name in the local club culture, known for his ability to read the crowd and craft sets that resonate on a deep level. His music is characterized by its hypnotic rhythms and atmospheric textures, making him a key player in Kosovo\'s electronic music landscape. As a resident at major local venues and events, Leart continues to shape the city\'s musical identity with his dedication to quality and his passion for creating memorable experiences on the dance floor.',
    links: { ra: 'https://ra.co/dj/leartrama/biography', instagram: 'https://www.instagram.com/leartrama/' },
    videoId: 'MqzNZUVM-Kw',
    videoLabel: 'Leart Rama — Nëntokë Podcast',
    tags: ['DJ', 'Producer'],
  },
  {
    id: 'rt',
    name: 'RT',
    realName: 'Art Bejtullahu',
    origin: 'Prishtinë',
    genres: ['Techno', 'Experimental'],
    bio: 'RT is an experimental DJ and producer from Gjakova, with experience in Germany and other countries and a unique approach to sound that blends techno with avant-garde influences. He has been a part of the local scene for many years, contributing to its growth and evolution with his innovative style and dedication to pushing boundaries. RT\'s music is characterized by its raw energy and experimental edge, making him a standout figure in Kosovo\'s electronic music landscape. With a focus on creating immersive sonic experiences, RT continues to influence the local scene with his forward-thinking approach and commitment to artistic exploration.And a very talented prodcuer when it comes to minimal and house music his tracks are being played by many djs around the world and he is a very important figure in the kKosovo underground scene.',
    links: { instagram: 'https://www.instagram.com/rt_bey/', soundcloud: 'https://soundcloud.com/slipthenet-bejtullahu' },
    videoId: 'e8cdB8y8rZQ',
    videoLabel: 'RT — Vinyl Youtube',
  },
  {
    id: 'pumio-space',
    name: 'Pumio Space',
    realName: 'Pëllumb Bekteshi',
    origin: 'Tirana',
    genres: ['Techno', 'Melodic'],
    bio: 'Pumio Space (Pëllumb Bekteshi) is a dedicated DJ, producer, and promoter from Ferizaj, Kosovo. He is a key figure in Kosovo’s underground electronic music scene, known for his deep commitment to authentic underground sounds as both a passionate record collector and producer.He is the founder of Playfest (an outdoor electronic music festival) and co-founder of the Playdrum collective and record label. Pumio Space has performed at major events including UNUM Festival and continues to play an important role in promoting and developing the local scene while releasing music on international labels..',
    links: { instagram: 'https://www.instagram.com/pumiospace/' },
    videoId: 'GXJtSgDnyUs',
    videoLabel: 'Pumio Space — Unum Festival Short',
    tags: ['DJ', 'Live Act'],
  },
  {
    id: 'alban-hi-dini',
    name: 'Alban Hi-Dini',
    realName: 'Alban Hajdini',
    origin: 'Tirana',
    genres: ['Minimal', 'Techno'],
    bio: 'Alban Hajdini, known as Alban Hi-Dini, is a DJ, producer, and sound engineer from Kosovo. He is a respected figure in the Balkan underground electronic music scene, known for his deep, groovy, and timeless selections heavily inspired by Chicago and Detroit sounds.With years of experience, he has performed at major events including UNUM Festival, Epizode Albania, and many parties in Prishtina. He also releases music internationally and continues to bring high-quality, musical sets to both local and international dancefloors.',
    links: { instagram: 'https://www.instagram.com/albanhi_dini/' },
    videoId: '0S2eJk_ITn4',
    videoLabel: 'Alban Hi-Dini b2b Rrrron — Unum Festival',
  },
  {
    id: 'toton',
    name: 'Toton',
    realName: 'Toton',
    origin: 'Prishtinë',
    genres: ['Techno', 'Open Format'],
    bio: 'Toton Pllana (known as Toton) is a veteran DJ, producer, and sound engineer from Prishtina, Kosovo. One of the pioneers of Kosovo’s underground electronic music scene, he was among the first to DJ in Prishtina after the war and helped establish the early underground dance culture as a member of the Undersound Collective.Known for his psychedelic grooves that fuse tech-house and techno, Toton has performed at major events including Boiler Room Kosovo, UNUM Festival, and various international showcases. He holds an MA in Audio Production from the University of Westminster and also runs his own studio.',
    links: { instagram: 'https://www.instagram.com/toton.music/' },
    videoId: 'h8WKCh5k8cQ',
    videoLabel: 'TOTON — Live YouTube Set',
  },
  {
    id: 'armir-bashota',
    name: 'Armir Bashota',
    realName: 'Armir Bashota',
    origin: 'Prishtinë',
    genres: ['Electronica', 'House'],
    bio: 'Armir is a Prishtina DJ and producer with an adventurous edge, playing genre-bending sets across the region.',
    links: { instagram: 'https://www.instagram.com/armirbashotta/' },
    videoId: 'Ax9WJJUc2_4',
    videoLabel: 'Armir Bashota — Teknik Set',
  },
  {
    id: 'leke',
    name: 'Lekë',
    realName: 'Lekë F. Berisha',
    origin: 'Prishtinë',
    genres: ['House', 'Minimal'],
    bio: 'Lekë is a Kosovan DJ known for polished minimal and melodic house mixes rooted in the club scene.',
    links: { instagram: 'https://www.instagram.com/leke.f.berisha/' },
    videoId: 'NWM88tWfRk8',
    videoLabel: 'Lekë — UNUM Festival 2021',
  },
  {
    id: 'artil',
    name: 'Artil',
    realName: 'Artil Qarkagjija',
    origin: 'Gjakova',
    genres: ['House', 'Techno'],
    bio: 'Artil is a Gjakova-born selector whose music blends warm house grooves with hypnotic melodic club energy.',
    links: { instagram: 'https://www.instagram.com/artil_dj/' },
    videoId: 'Rsb9_KrS7sE',
    videoLabel: 'Artil — YouTube Video',
  },
  {
    id: 'tezz',
    name: 'Tezz',
    realName: 'Tez Latifi',
    origin: 'Prishtinë',
    genres: ['DnB', 'Open Format'],
    bio: 'Tezz is a dynamic DJ and producer whose range moves from drum & bass to open-format club sets.',
    links: { instagram: 'https://www.instagram.com/tezzito/' },
    videoId: '98Zlk633dUQ',
    videoLabel: 'Tezz — YouTube Video',
  },
  {
    id: 'secret-47',
    name: 'Secret 47',
    realName: 'Gentian Rizaj',
    origin: 'Prishtinë',
    genres: ['Techno', 'House'],
    bio: 'Secret 47 is a high-profile Kosovan DJ recognized for major festival appearances and deep club performances.',
    links: { instagram: 'https://www.instagram.com/secret47file/' },
    videoId: '7gSgeHipFkE',
    videoLabel: 'Secret 47 — Unum Festival Main Stage',
  },
  {
    id: 'giza',
    name: 'Giza',
    realName: 'Giza Berisha',
    origin: 'Prishtinë',
    genres: ['House', 'Techno'],
    bio: 'Giza is a Kosovo-based selector and producer exploring melodic house, techno and modern club sounds.',
    links: { instagram: 'https://www.instagram.com/gizabert/' },
    videoId: '',
    videoLabel: 'Video Coming Soon',
  },
  {
    id: 'leg-off',
    name: 'Leg Off',
    realName: 'Mentor Peci',
    origin: 'Prishtinë',
    genres: ['House', 'Techno'],
    bio: 'Mentor Peci is a Kosovo DJ and party curator with a sharp feel for underground club programming.',
    links: { instagram: 'https://www.instagram.com/leg__off/' },
    videoId: 'qzb7LwObvMc',
    videoLabel: 'Mentor Peci — YouTube Video',
  },
  {
    id: 'kresha-tech',
    name: 'Kresha Tech',
    realName: 'Kreshnik',
    origin: 'Prishtinë',
    genres: ['Techno', 'Acid'],
    bio: 'Kresha Tech is a leading voice in Kosovo techno, combining raw energy with precise, peak-hour selections.',
    links: { instagram: 'https://www.instagram.com/kreshatech/' },
    videoId: 'vSfcfxaKX0w',
    videoLabel: 'Kresha Tech — Essential Mix',
  },
  {
    id: 'almarin',
    name: 'ALMARIN',
    realName: 'Almarin Gjinovci',
    origin: 'Prishtinë',
    genres: ['Techno', 'Melodic'],
    bio: 'ALMARIN is a newer voice from the region, bringing melodic techno and driving club sets to major Balkan stages.',
    links: { instagram: 'https://www.instagram.com/almaringjinovci/' },
    videoId: 'GMzqsveSIcU',
    videoLabel: 'ALMARIN — Ngom Fest Live Short',
  },
  {
    id: 'rt-art-bejtullahu',
    name: 'RT Art Bejtullahu',
    realName: 'RT Art Bejtullahu',
    origin: 'Prishtinë',
    genres: ['Techno', 'House'],
    bio: 'RT Art Bejtullahu is a Kosovo artist contributing to the electronic music scene.',
    links: {},
    videoId: 'e8cdB8y8rZQ',
    videoLabel: 'RT Art Bejtullahu — YouTube Video',
  },

  {

    id: 'neritaan',

    name: 'Neritaan',

    realName: 'Neritaan',

    origin: 'Kosovo',

    genres: ['Minimal', 'Deep Tech'],

    bio: "Neritaan is a DJ and producer of electronic music with minimal deep tech preferences. Find more at https://www.beatport.com/artist/neritaan/926976 and linktr.ee/neritaan",

    links: { soundcloud: 'https://soundcloud.com/neritaan', bandcamp: 'https://jusluvrecordings.bandcamp.com/album/cellophane-dreams-ep' },

    videoId: '',

    videoLabel: 'Video Coming Soon',

  },

]

export const events = [
  {
    id: 'mihai-popoviciu-next-level',
    title: 'MIHAI POPOVICIU - NEXT LEVEL',
    subtitle: 'An Experimental Concept',
    date: '2026-05-08',
    time: '22:00',
    venue: 'AMC HALL STAGE 2',
    address: 'Prishtina, Kosovo',
    lineup: ['Mihai Popoviciu', 'La Baresha', 'Baxel', 'MiM'],
    description: 'A new experimental concept where the night unfolds phase by phase, a journey through sound, atmosphere, and energy. It will be held in Prishtina at AMC Hall Stage 2, Kosovo. Featuring Romanian legend and Cyclic Records boss Mihai Popoviciu, supported by rising female talent La Baresha, old school selector Baxel, and MiM — a key figure in Kosovo\'s electronic music movement.',
    ticketLink: 'https://www.rave-travel.com/event-details-en.nspx?eventid=4098',
    price: '€10 advance / €15 at door',
    soldOut: false,
    featured: true,
    posterColor: '#cc1111',
  },
  {
    id: 'marcel-dettmann-rave',
    title: 'MARCEL DETTMANN - RAVE',
    subtitle: 'Berlin Techno Legend',
    date: '2026-05-15',
    time: '21:00',
    venue: 'AMC HALL',
    address: 'Prishtina, Kosovo',
    lineup: ['Marcel Dettmann', 'Elli Acula', 'George Adi', 'Uran B'],
    description: 'On 15 May, Prishtina will host one of the most significant electronic music lineups announced this season. Headlining the night is Marcel Dettmann, a central figure of Berlin\'s techno movement and one of the most respected names associated with Berghain\'s legacy. Joining him is Elli Acula, one of the most in-demand artists of the new European techno wave, known for her high-energy, genre-blending sets across major international stages. Completing the lineup are regional representatives George Adi and Uran B, reinforcing the connection between the international underground circuit and the local scene. The event will take place at AMC Hall and is expected to bring together audiences from across Kosovo and the region, marking a key moment in this year\'s electronic music calendar.',
    ticketLink: 'https://www.rave-travel.com/tickets-en.nspx?eventid=4055',
    price: '€15',
    soldOut: false,
    featured: true,
    posterColor: '#000000',
  },
  {
    id: 'unum-festival',
    title: 'UNUM FESTIVAL',
    subtitle: '5 Days Non-Stop Music',
    date: '2026-06-04',
    time: 'Thu–Mon, 24h non-stop',
    venue: 'Set Beach',
    address: 'Shengjin, Albania',
    lineup: ['Ben Klock', 'Ricardo Villalobos', 'Gerd Janson', 'Dan Andrei', 'Maher Daniel', 'Prospa', '+ 50+ International DJs'],
    description: 'Winner of Global Festival DJ Awards Ibiza 2025. Five days of non-stop electronic music against the backdrop of the Albanian Riviera. Multiple stages, beachfront location, and world-class international lineup.',
    ticketLink: 'https://unumfestival.com/tickets',
    price: '€150–€250 festival pass',
    soldOut: false,
    featured: true,
    posterColor: '#1a4f3a',
  },
  {
    id: 'sundance-festival',
    title: 'SUNDANCE FESTIVAL',
    subtitle: 'Mountain Electronic Experience',
    date: '2026-07-09',
    time: 'Wed–Sat, 20:00–06:00',
    venue: 'Zvërnec',
    address: 'Zvërnec, Albania',
    lineup: ['International Techno Artists', 'Albanian DJs', 'Live Performances', 'Ambient Sets'],
    description: 'Four days of electronic music in the stunning Albanian mountains. Set against breathtaking natural scenery, Sundance Festival combines world-class DJs with immersive art installations and mountain views.',
    ticketLink: 'https://sundance-festival.com/',
    price: '€100–€180 festival pass',
    soldOut: false,
    featured: true,
    posterColor: '#2a4f6a',
  },
  {
    id: 'sunny-hill-festival',
    title: 'SUNNY HILL FESTIVAL',
    subtitle: 'Dua Lipa Presents',
    date: '2026-07-31',
    time: 'Wed–Fri, 18:00–02:00',
    venue: 'Sunny Hill Festival Park',
    address: 'Prishtinë, Kosovo',
    lineup: ['Dua Lipa', 'International Headliners TBA', 'Kosovo Artists', 'Regional Stars'],
    description: 'Kosovo\'s premier music festival organized by global superstar Dua Lipa. Winner of the Economic Impact Award from Kosovo Chamber of Commerce. Three days of world-class entertainment celebrating Kosovo culture and international music.',
    ticketLink: 'https://sunnyhillfestival.com/tickets',
    price: '€80–€150 weekend pass',
    soldOut: false,
    featured: true,
    posterColor: '#f0eb3a',
  },
]
